name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v4
      - uses: actions/setup-node@v6
        with:
          cache: "yarn"
      - run: yarn install

      - name: Build plugin
        run: yarn build

      # Wait for tests to finish successfully
      - uses: ArcticLampyrid/action-wait-for-workflow@v1.3.0
        with:
          workflow: verify.yml
          wait-interval: 10

      # Recommended Release Workflow
      # https://docs.obsidian.md/Plugins/Releasing/Release+your+plugin+with+GitHub+Actions
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          FLAGS="--title=$tag"
          if [[ "${{ github.ref }}" == *"beta"* ]]; then
            FLAGS="$FLAGS --prerelease"
          fi

          gh release create "$tag" \
            $FLAGS \
            main.js manifest.json styles.css
