name: Release

on:
  workflow_run:
    workflows: [Verify]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    # Only run the job if "Verify" completed successfully, and we're
    # operating on a tag
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v4
      - uses: actions/setup-node@v6
        with:
          cache: "yarn"
      - run: yarn install

      - name: Build plugin
        run: yarn build

      # Recommended Release Workflow
      # https://docs.obsidian.md/Plugins/Releasing/Release+your+plugin+with+GitHub+Actions
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            main.js manifest.json styles.css
